name: assetaudit

description: "asset audit project."

publish_to: 'none' 

version: 1.0.1+6

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  shared_preferences: ^2.2.3
  mobile_scanner: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"